#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -D /tmp # working directory
#SBATCH -t 0-00:05 # Runtime in D-HH:MM
#SBATCH -p dcc # Partition to submit to
#SBATCH --mem 2048 # 2GB solicitados.
#SBATCH --gres gpu:Pascal:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written 
echo $CUDA_VISIBLE_DEVICES >> /home/yaxing/ACM-MM/StarGAN_noise_attention_concat_label_with_image/logs/${SLURM_JOB_ID}

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/results --selected_attrs 5_o_Clock_Shadow Arched_Eyebrows Attractive Bags_Under_Eyes Bald --lambda_noise 0 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels6_10/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels6_10/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels6_10/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels6_10/results --selected_attrs Bangs Big_Lips Big_Nose Black_Hair Blond_Hair --lambda_noise 0 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels11_15/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels11_15/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels11_15/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels11_15/results --selected_attrs Blurry Brown_Hair Bushy_Eyebrows Chubby Double_Chin --lambda_noise 0 --attention True 


#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels16_20/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels16_20/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels16_20/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels16_20/results --selected_attrs Eyeglasses Goatee Gray_Hair Heavy_Makeup High_Cheekbones --lambda_noise 0 --attention True


#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/results --selected_attrs Male Mouth_Slightly_Open Mustache Narrow_Eyes No_Beard --lambda_noise 0 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels26_30/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels26_30/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels26_30/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels26_30/results --selected_attrs  Oval_Face Pale_Skin Pointy_Nose Receding_Hairline Rosy_Cheeks --lambda_noise 0 --attention True 

#python main.py --mode train --dataset CelebA --celeba_image_dir data/celeba/images --attr_path data/celeba/list_attr_celeba.txt --image_size 128 --c_dim 5 --sample_dir results/samples --log_dir results/logs  --model_save_dir results/models --result_dir results/results --selected_attrs  Sideburns Bangs Blond_Hair Brown_Hair Male Eyeglasses  --lambda_noise 800 --attention True 
python main.py --mode train --dataset CelebA --celeba_image_dir ../StarGAN/data/celeba/images --attr_path ../StarGAN/data/celeba/list_attr_celeba.txt --image_size 128 --c_dim 5 --sample_dir results/samples --log_dir results/logs  --model_save_dir results/models --result_dir results/results --selected_attrs  Sideburns Bangs Blond_Hair Brown_Hair Male Eyeglasses  --lambda_noise 800 --attention True 
#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels21_25/results --selected_attrs Male Mouth_Slightly_Open Mustache Narrow_Eyes No_Beard Oval_Face Pale_Skin Pointy_Nose Receding_Hairline Rosy_Cheeks Sideburns Smiling Straight_Hair Wavy_Hair Wearing_Earrings Wearing_Hat Wearing_Lipstick Wearing_Necklace Wearing_Necktie Young --lambda_noise 0 --attention True 


#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 40 --sample_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/samples --log_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/models --result_dir stargan_celeba/lambda_noise_0_attention_true/labels1_5/results --selected_attrs 5_o_Clock_Shadow Arched_Eyebrows Attractive Bags_Under_Eyes Bald Bangs Big_Lips Big_Nose Black_Hair Blond_Hair Blurry Brown_Hair Bushy_Eyebrows Chubby Double_Chin Eyeglasses Goatee Gray_Hair Heavy_Makeup High_Cheekbones Male Mouth_Slightly_Open Mustache Narrow_Eyes No_Beard Oval_Face Pale_Skin Pointy_Nose Receding_Hairline Rosy_Cheeks Sideburns Smiling Straight_Hair Wavy_Hair Wearing_Earrings Wearing_Hat Wearing_Lipstick Wearing_Necklace Wearing_Necktie Young --lambda_noise 0 --attention True 







#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_50_attention_true/samples --log_dir stargan_celeba/lambda_noise_50_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true/models --result_dir stargan_celeba/lambda_noise_50_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 50 --attention True

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 100 --attention True 

#python main.py --mode train --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/samples --log_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/models --result_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young  --lambda_noise 0 --attention True 




###########Test###########
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 200000

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 190000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 180000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 170000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 160000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 150000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 140000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 130000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 120000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 110000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 100000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 90000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 80000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 70000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 60000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 50000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 40000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 30000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 20000
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_10_attention_true/samples --log_dir stargan_celeba/lambda_noise_10_attention_true/logs  --model_save_dir stargan_celeba/lambda_noise_10_attention_true/models --result_dir stargan_celeba/lambda_noise_10_attention_true/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young --lambda_noise 10 --attention True  --sample_dim 20 --test_iters 10000
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 190000 
#
##
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 200000 
#
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 180000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 170000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 160000 
# 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 150000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 140000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 130000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 120000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 110000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 100000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 90000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 80000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 70000 
# 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 60000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 50000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 40000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 30000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 20000 
#
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_50_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 50 --attention True  --test_iters 10000 

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_100_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 100 --attention True  --test_iters 200000 

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 --sample_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/samples --log_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/logs  --model_save_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/models --result_dir stargan_celeba/lambda_noise_0_attention_true_c_dim_5/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young  --lambda_noise 0 --attention True --test_iters 90000 

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True 

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 190000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 180000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 170000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 160000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 150000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 140000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 130000 
#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 120000 
#python main.py --mode test_attention --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 200000 

#python main.py --mode test_attention --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 150000 
#
#python main.py --mode test_attention --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 100000 
#
#python main.py --mode test_attention --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 50000 
#
#python main.py --mode test_attention --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 10000 

#python main.py --mode test_save_test_image --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True  

#python main.py --mode test --dataset CelebA --image_size 128 --c_dim 10 --sample_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/samples --log_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/logs  --model_save_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/models --result_dir stargan_celeba/lambda_noise_20_attention_true_c_dim_10/results --selected_attrs Bangs Blond_Hair Brown_Hair Male Young Eyeglasses Wearing_Hat Smiling Pale_Skin Mouth_Slightly_Open --lambda_noise 20 --attention True --test_iters 100000 
#
 

/usr/local/cuda/samples/bin/x86_64/linux/release/clock
echo $CUDA_VISIBLE_DEVICES >> /home/yaxing/ACM-MM/StarGAN_noise_attention_concat_label_with_image/logs/${SLURM_JOB_ID}

